### ISSUE TITLE
Add kanji drawing quiz

### ISSUE THREAD

**Issue by abderrahim** [blastrock/kaqui#2]
It would be nice to have a hard mode or something for quizzes where the answer is a kanji by requiring the user to write the kanji rather than selecting it among the possible choices.

[kanjirecog](https://github.com/quen/kanjirecog) is a library that can be used for this (an android app is in the `android` branch).

**Comment by blastrock** [comment]
Sorry, github didn't notify me about issues on my repo, I am seeing this only now.

Yup, I don't have much time right now, but kanji drawing is the next feature I have planned.
