### ISSUE TITLE
Crash when tapping on a kanji

### ISSUE THREAD

**Issue by abderrahim** [blastrock/kaqui#4]
When tapping on a kanji I get the following exception, probably because I don't have aedict3 installed. 

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference`

The stack trace isn't very informative because the method names are cut out but it should be possible to find the problem by looking at where startActivity is called.
```
 	at android.app.Activity.startActivity(Activity.java:4494)
 	at org.kaqui.QuizzActivity.a(Unknown Source)
 	at org.kaqui.QuizzActivity.a(Unknown Source)
 	at org.kaqui.QuizzActivity$j.onClick(Unknown Source)
```

**Comment by blastrock** [comment]
This seems to work now, please reopen if the bug is still there.
